name: workflow-docker-manual

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tag name for test/dev image'
        default: 'test'

jobs:
  gcr-dockerhub-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-arch support
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Sync GitHub README.md with Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # NOTE: This MUST be the password NOT the token
          repository: ${{ steps.lower-repo.outputs.repository }}
          short-description: ${{ github.event.repository.description }}
      - name: DEBUG Show Runners environment
        shell: bash
        run: |
            export
      - name: Generate temporary tag name
        shell: bash
        run: |
          test_tag=$(date +%Y%m%d%H%M%S)
          echo "[debug] Generated test tag name is '${test_tag}'"
          echo "test_tag=$test_tag" >> $GITHUB_OUTPUT
        id: generate_temporary_tag_name
      - name: Generate app name
        shell: bash
        run: |
          app_name=$(echo "${GITHUB_REPOSITORY}" | grep -P -o -m 1 '(?<=/arch-).*')
          echo "[debug] Generated app name is '${app_name}'"
          echo "app_name=$app_name" >> $GITHUB_OUTPUT
        id: generate_app_name
      - name: Lower repo name
        id: lower-repo
        shell: pwsh
        run: |
          echo "repository=$($env:GITHUB_REPOSITORY.ToLowerInvariant())" >> $env:GITHUB_OUTPUT
      - name: Build multi-arch Docker image, tag and push to registries
        uses: Wandalen/wretry.action@v3
        with:
          action: docker/build-push-action@v6
          with: |
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ steps.lower-repo.outputs.repository }}:${{ github.event.inputs.tags }}, quay.io/${{ steps.lower-repo.outputs.repository }}:${{ github.event.inputs.tags }}, ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.event.inputs.tags }}, registry.gitlab.com/${{ steps.lower-repo.outputs.repository }}:${{ github.event.inputs.tags }}
            build-args: |
              RELEASETAG=${{ github.event.inputs.tags }}
          attempt_limit: 3
          attempt_delay: 600000
